'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.42000
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Fonctionnalité Enregistrement automatique My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ComboBox_daq01() As Integer
            Get
                Return CType(Me("ComboBox_daq01"),Integer)
            End Get
            Set
                Me("ComboBox_daq01") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property ComboBox_daq02() As Integer
            Get
                Return CType(Me("ComboBox_daq02"),Integer)
            End Get
            Set
                Me("ComboBox_daq02") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public Property ComboBox_daq03() As Integer
            Get
                Return CType(Me("ComboBox_daq03"),Integer)
            End Get
            Set
                Me("ComboBox_daq03") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("3")>  _
        Public Property ComboBox_daq04() As Integer
            Get
                Return CType(Me("ComboBox_daq04"),Integer)
            End Get
            Set
                Me("ComboBox_daq04") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("4")>  _
        Public Property ComboBox_daq05() As Integer
            Get
                Return CType(Me("ComboBox_daq05"),Integer)
            End Get
            Set
                Me("ComboBox_daq05") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("5")>  _
        Public Property ComboBox_daq06() As Integer
            Get
                Return CType(Me("ComboBox_daq06"),Integer)
            End Get
            Set
                Me("ComboBox_daq06") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("6")>  _
        Public Property ComboBox_daq07() As Integer
            Get
                Return CType(Me("ComboBox_daq07"),Integer)
            End Get
            Set
                Me("ComboBox_daq07") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("7")>  _
        Public Property ComboBox_daq08() As Integer
            Get
                Return CType(Me("ComboBox_daq08"),Integer)
            End Get
            Set
                Me("ComboBox_daq08") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("8")>  _
        Public Property ComboBox_daq09() As Integer
            Get
                Return CType(Me("ComboBox_daq09"),Integer)
            End Get
            Set
                Me("ComboBox_daq09") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
        Public Property ComboBox_daq10() As Integer
            Get
                Return CType(Me("ComboBox_daq10"),Integer)
            End Get
            Set
                Me("ComboBox_daq10") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property ComboBox_daq11() As Integer
            Get
                Return CType(Me("ComboBox_daq11"),Integer)
            End Get
            Set
                Me("ComboBox_daq11") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("11")>  _
        Public Property ComboBox_daq12() As Integer
            Get
                Return CType(Me("ComboBox_daq12"),Integer)
            End Get
            Set
                Me("ComboBox_daq12") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property ComboBox_affectation01() As Integer
            Get
                Return CType(Me("ComboBox_affectation01"),Integer)
            End Get
            Set
                Me("ComboBox_affectation01") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property ComboBox_affectation02() As Integer
            Get
                Return CType(Me("ComboBox_affectation02"),Integer)
            End Get
            Set
                Me("ComboBox_affectation02") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property ComboBox_affectation03() As Integer
            Get
                Return CType(Me("ComboBox_affectation03"),Integer)
            End Get
            Set
                Me("ComboBox_affectation03") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public Property ComboBox_affectation04() As Integer
            Get
                Return CType(Me("ComboBox_affectation04"),Integer)
            End Get
            Set
                Me("ComboBox_affectation04") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public Property ComboBox_affectation05() As Integer
            Get
                Return CType(Me("ComboBox_affectation05"),Integer)
            End Get
            Set
                Me("ComboBox_affectation05") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public Property ComboBox_affectation06() As Integer
            Get
                Return CType(Me("ComboBox_affectation06"),Integer)
            End Get
            Set
                Me("ComboBox_affectation06") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ComboBox_affectation07() As Integer
            Get
                Return CType(Me("ComboBox_affectation07"),Integer)
            End Get
            Set
                Me("ComboBox_affectation07") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ComboBox_affectation08() As Integer
            Get
                Return CType(Me("ComboBox_affectation08"),Integer)
            End Get
            Set
                Me("ComboBox_affectation08") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ComboBox_affectation09() As Integer
            Get
                Return CType(Me("ComboBox_affectation09"),Integer)
            End Get
            Set
                Me("ComboBox_affectation09") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ComboBox_affectation10() As Integer
            Get
                Return CType(Me("ComboBox_affectation10"),Integer)
            End Get
            Set
                Me("ComboBox_affectation10") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ComboBox_affectation11() As Integer
            Get
                Return CType(Me("ComboBox_affectation11"),Integer)
            End Get
            Set
                Me("ComboBox_affectation11") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ComboBox_affectation12() As Integer
            Get
                Return CType(Me("ComboBox_affectation12"),Integer)
            End Get
            Set
                Me("ComboBox_affectation12") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("582611,582686,583206,583433,583447,583457,588686,588850,589036,589048,589129,5891"& _ 
            "62,589184")>  _
        Public Property phidget_list() As String
            Get
                Return CType(Me("phidget_list"),String)
            End Get
            Set
                Me("phidget_list") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("750")>  _
        Public Property threadingtime_BEFORE() As Integer
            Get
                Return CType(Me("threadingtime_BEFORE"),Integer)
            End Get
            Set
                Me("threadingtime_BEFORE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("750")>  _
        Public Property threadingtime_AFTER() As Integer
            Get
                Return CType(Me("threadingtime_AFTER"),Integer)
            End Get
            Set
                Me("threadingtime_AFTER") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("60000")>  _
        Public Property Timer_START_DAQ_Interval() As Integer
            Get
                Return CType(Me("Timer_START_DAQ_Interval"),Integer)
            End Get
            Set
                Me("Timer_START_DAQ_Interval") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property checkbox_autofill_samplenames() As Boolean
            Get
                Return CType(Me("checkbox_autofill_samplenames"),Boolean)
            End Get
            Set
                Me("checkbox_autofill_samplenames") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("c:\")>  _
        Public Property default_folder() As String
            Get
                Return CType(Me("default_folder"),String)
            End Get
            Set
                Me("default_folder") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2021_01_04_calibration.csv")>  _
        Public Property default_cal_file() As String
            Get
                Return CType(Me("default_cal_file"),String)
            End Get
            Set
                Me("default_cal_file") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("12")>  _
        Public Property NumUpDown_nbofdev() As Integer
            Get
                Return CType(Me("NumUpDown_nbofdev"),Integer)
            End Get
            Set
                Me("NumUpDown_nbofdev") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("08/01/2021 10:55:15,_,ZERO,,,,,,,,,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-999"& _ 
            "9,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,"& _ 
            "-9999,-9999,-9999,-9999,-9999,-9999,-9999,3.27826E-07,-1.6205E-07,-1.5201978E-05"& _ 
            ",6.402843E-06,-1.073815E-06,-1.611188E-06,5.116686E-06,8.789822E-06,-9999,-9999,"& _ 
            "-9999,-9999,2.047047E-06,-2.9926188E-05,1.098961E-06,6.686896E-06,-9999,-9999,-9"& _ 
            "999,-9999,")>  _
        Public Property zero_res() As String
            Get
                Return CType(Me("zero_res"),String)
            End Get
            Set
                Me("zero_res") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.cuticular.My.MySettings
            Get
                Return Global.cuticular.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
